### ISSUE TITLE
Refactor of Contract/Solidity

### ISSUE THREAD

**Issue by itamarcps** [SparqNet/orbitersdk-cpp#6]
Refactor of the Contract class following the new Contract's Concept/Behaviour

**Comment by itamarcps** [comment]
This refactor was finished with the commit 4de34dac4c45f2aca425d84849459ac99899d2eb a while ago, only missing documentation, problem is #21 #22 #30 now exist which will ultimately change the contract folder again, necessitating another documentation upgrade, #21 is already being worked on and should be finished soon, I believe we can on focus on implementing reflections first, as it will dramatically change the documentation for how ContractManager works and how DynamicContract are created in the runtime, opinions @Jean-Lessa  @jcarraror ?

**Comment by jcarraror** [comment]
Commits [6a37957](https://github.com/SparqNet/orbitersdk-cpp/commit/6a379577c89bb5c0ba6c812094e1c3dd66109bdf) and [836f31d](https://github.com/SparqNet/orbitersdk-cpp/commit/836f31d1006ec498dee5edf4a220e1986eda0b6c) documented the contract folder. I think that this issue can be closed for now because reflection issues will deal with each particular refactor in the contracts. #30 will be finalized first, so the other issues can just take advantage of the infrastructure of reflection that will be introduced.
