### ISSUE TITLE
Contract Manager Refactoring

### ISSUE THREAD

**Issue by itamarcps** [SparqNet/orbitersdk-cpp#70]
• Motivation: The current ContractManager design bears the burden of too many responsibilities, including contract creation, acting as the entry point for Dynamic Contract calls, interfacing nested calls, and handling contract native balance operations via the ContractManagerInterface. Additionally, it is responsible for storing accessed contract variables and reverting them. Uniquely, developers have to manually integrate Protocol Contract transaction access, adding to the complexity of the ContractManager class. This accumulation of duties results in code smell and potential exploits, especially within nested contract calls.

• Objective: Enhance the architecture of the ContractManager, aiming to compartmentalize tasks such as contract creation, accessing, and interfacing with other contracts, leading to a more secure and maintainable code base.

• Success Criteria: Effective distribution of tasks with a particular focus on the handling of nested contract calls, a recognized area of potential vulnerability.

• Dependencies: This task does not expect to introduce any new external dependencies.

• Risks and Mitigations: The complexity of this task is not to be understated. The current state of the ContractManager has led to various unforeseen behaviors, chiefly related to the capacity of contracts to spawn other contracts and enable nested calls. Therefore, careful design and thorough testing will be necessary to ensure robustness.

• Resource Allocation: The refactoring of the ContractManager will affect the Contract Manager Interface (CMI) and all DynamicContracts that require access to the interface for operations such as consulting/spending native balance, calling other contracts, etc. In light of this, it might be prudent to develop RAII objects that serve as contract accessors during a single transaction call lifetime.

Key Considerations:

Dynamic Contracts can only be called by a transaction from a block in process. 
Simulations of transactions should be fully reversible. 
Contracts that are being called can create new Dynamic Contracts and call other contracts' functions. 
In the event of a throw, all accessed contracts must revert their internal variables, that also includes native balances that have been updated.

**Comment by Jean-Lessa** [comment]
One of the possible ways this could be done, we can work this out as we go (all names described are merely suggestions):

* **ContractManager** would be responsible only for maintaining the list of registered contracts and nothing more
  * IIRC it only deals with *Dynamic Contracts*, but maybe it could have a separate part of it *or* an entirely new class to only hold Protocol Contracts, making it easier for users to register both when they see fit (not sure if this is feasible)
* **ContractManagerInterface** stays as it is, since it's meant to act as a middleman between external contract calls and the ContractManager anyway - at the very least I would suggest renaming it to just **ContractInterface** and putting it in its own header like `src/contract/contractinterface.h`
* **ContractFactory** or **ContractDeployer** - A class dedicated to the portion of only creating/deploying contracts
  * Its constructor takes a reference to the ContractManager
  * The contract creation functions (`setupNewContract()`, `createNewContract()`, `createContractWithTuple()` and all of its helpers if necessary) are migrated from ContractManager to it
  * A function like `deployContract()` would take the contract object itself as an argument, and all it would do is add it to the manager's list
* **ContractCallBuffer** - A struct or class dedicated to abstracting nested contract call chains. It could contain a `vector<tuple<Contract*, SafeBase*, oldValueString, newValueString>>` or similar structure that would track variable changes from start to finish (the pointer to the contract that started the call could either be the first on this list, *or* an entirely separate variable in the class if necessary), plus helper functions to manipulate the list itself
  * This is on purpose - each instance would effectively encapsulate a specific nested call regardless of the starting contract, which means we could handle and order multiple nested calls originating from the same contract, something that would be impossible or downright cumbersome to do with a simple `unordered_map`
* **ContractCallTable** - A class dedicated to maintaining a global list of nested contract call chains
  * All it does is maintain a `vector<ContractCallBuffer>` or a similar structure and use helper functions to effectively manipulate it and do the commit/revert operations on each
  * Helper functions could include: `commitAll()` and `revertAll()` (iterating through the whole list), `commitOnly()` and `revertOnly()` (iterating through a specific object from the list, for a finer control/granularity)
  * This logic is essentially (more or less) how Git works - this would be equivalent to the "staging area", while the ContractCallBuffer objects by themselves could be considered the "working tree"

@itamarcps @jcarraror Would like a second opinion and/or a finer revision of this logic - there might be some caveats I'm not aware of.

**Comment by jcarraror** [comment]
I really think the general idea is good, but I believe that separating the ContractInterface from the Manager can add a greater layer of complexity, as it would lead to many circular dependencies and multiple references. I don't consider that interface classes within the definition of the class to be interfaced (in our case, CMI within the CM) is an architectural problem. In any case, if we decide to separate the interface, it will be important to take great care in refactoring the files that use it.

**Comment by Jean-Lessa** [comment]
I just pushed a new branch `70-cm-refactor` with the first step of decoupling - ContractFactory was implemented and decoupled from ContractManager (commit [d6bc54d](https://github.com/SparqNet/orbitersdk-cpp/commit/d6bc54dfe9d71e45f265c451a2f4600a51f81a08), for some reason GitHub is not showing it here in the comment history).

So now ContractFactory handles everything related to contract creation and deploying (all of CM's contract creation functions were migrated to it), and ContractManager itself now only handles loading contracts from the database, and the usual ethCalls and function processing.

Running tests with the `[contract]` label yielded no errors, so i'm assuming everything is fine for now. Would appreciate further feedback with proper real-world testing if you deem it necessary.

**Comment by jcarraror** [comment]
Regarding the event feature, i will let some ideas here for further discussions:

Structure:

```c++
class Event {
private:
    std::string name;
    std::unordered_map<std::string, std::string> parameters; // nome, tipo

public:
    Event(const std::string& eventName) : name(eventName) {}

    // add paramentro no evento
    void addParameter(const std::string& paramName, const std::string& paramType) {
        ...
    }

    // getters e etc ...
    std::string getName() const { return name; }
    std::unordered_map<std::string, std::string> getParameters() const { return parameters; }
....
};
```

Manager:

```c++
class EventManager {
private:
    std::vector<std::shared_ptr<Event>> eventsRegistry;

public:
    void registerEvent(const std::shared_ptr<Event>& event) { //PRECISA ser shared_ptr
        ....
    }

    void emitEvent(const std::shared_ptr<Event>& event, const std::unordered_map<std::string, std::string>& parameters) {
        ...    }

///mais funções ao passo que for necessário
};
```
Use example:

```c++
std::shared_ptr<Event> TransferEvent = std::make_shared<Event>("Transfer");
TransferEvent->addParameter("from", "Address");
TransferEvent->addParameter("to", "Address");
TransferEvent->addParameter("value", "uint256_t");

EventManager eventManager;
eventManager.registerEvent(TransferEvent);
```

**Comment by Jean-Lessa** [comment]
Branch should now have part two of the decoupling in commit [18fa9b8](https://github.com/SparqNet/orbitersdk-cpp/commit/18fa9b8716363c5d27ca6dc49c936f6b8fd08db0) - alterations in contract SafeVariables and balances are now delegated to a new class called **ContractCallState** (former "ContractCallBuffer", this name feels a bit more fitting), initialized inside ContractManager itself just like ContractFactory. The `usedVars` and `balances` lists that were in CM were migrated to it, along with a few helper functions to further encapsulate and abstract their manipulation.

Also the idea of what would be the "ContractCallTable" has been dropped due to me better understanding how the `usedVars` and `balances` lists worked inside CM, AFAICT apparently we won't need that since the current code is already operating on an "atomic commit/revert logic", and there's no possibility of two nested contract calls happening at the same time (it's always one after the other and there's no interference from either, and both lists are always cleaned up at the end of a nested call), so yeah that's that.

`[contract]` tests remain clean, you can test it yourselves if you want, same as usual.
